spring:
  datasource:
    username: root
    password: root1234
    url: jdbc:mysql://localhost:3306/mymovies


  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB


  mail:
    host: smtp.gmail.com
    port: 587
    username: "techandrewwilliam@gmail.com"
    password: "kxrd hizk yfry meiy"
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

project:
  image: image/

base:
    url: "http://localhost:8080"
